import { createHmac, timingSafeEqual } from "node:crypto";

// One-click unsubscribe has to work with no login, which means the link
// itself must prove it was really generated by this server for this exact
// address — otherwise it could be replayed to suppress an arbitrary
// competitor's email. HMAC-signing the address is the same approach
// auth.ts uses for the admin session cookie, kept as its own function so a
// leak of one signature scheme is never a skeleton key for the other.
//
// Encoded as one opaque path segment (base64url email + a short signature),
// not a "?email=...&token=..." query string: a visible key=value pair is
// the single most obvious "generated by mail-merge software" tell there is,
// and the entire point of this campaign is reading like it wasn't. Nothing
// here is a real authentication boundary — this only ever gates "add this
// address to the suppression list" — so a 64-bit truncated signature is
// proportionate.
function getSecret() {
  return (
    process.env.SESSION_SECRET ||
    process.env.DATABASE_URL ||
    "patchbay-unsubscribe-fallback"
  );
}

function sign(email: string) {
  return createHmac("sha256", getSecret())
    .update(`unsubscribe:${email.toLowerCase().trim()}`)
    .digest("hex")
    .slice(0, 16);
}

export function makeUnsubscribeSlug(email: string) {
  const enc = Buffer.from(email.toLowerCase().trim(), "utf8").toString("base64url");
  return `${enc}.${sign(email)}`;
}

/** Returns the email address if the slug is genuine, otherwise null. */
export function parseUnsubscribeSlug(slug: string): string | null {
  const dot = slug.lastIndexOf(".");
  if (dot === -1) return null;

  let email: string;
  try {
    email = Buffer.from(slug.slice(0, dot), "base64url").toString("utf8");
  } catch {
    return null;
  }
  if (!email.includes("@")) return null;

  const given = slug.slice(dot + 1);
  const expected = sign(email);
  const a = Buffer.from(given);
  const b = Buffer.from(expected);
  if (a.length !== b.length) return null;
  if (!timingSafeEqual(a, b)) return null;

  return email;
}
